# Generated by Django 6.0.7 on 2026-07-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('is_predatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('interest_rate', 'Excessive Interest Rate'), ('hidden_fees', 'Hidden Fees'), ('harassment_sms', 'Harassment via SMS/Calls'), ('data_privacy', 'Data Privacy Violation'), ('unlicensed_lender', 'Unlicensed Lender'), ('fraud', 'Fraud / Impersonation')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.lender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(choices=[('BoU', 'Bank of Uganda'), ('UMRA', 'Uganda Microfinance Regulatory Authority'), ('UCC', 'Uganda Communications Commission'), ('FIA', 'Financial Intelligence Authority')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='core.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('is_repaid', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False)),
                ('raw_sms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.lender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('Stable', 'Stable'), ('Emerging Risk', 'Emerging Risk'), ('High Risk', 'High Risk')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stress_assessment', to='core.borrower')),
            ],
        ),
    ]
